### ISSUE TITLE
"Warning:  deprecated style: a semi-colon is not needed here"

### ISSUE THREAD

**Issue by CarlKCarlK** [dafny-lang/libraries#140]
I'm seeing many warnings of the form:

```
o:\Projects\Science\dafny\libraries\src\Collections\Sequences\Seq.dfy(138,32): Warning: deprecated style: a semi-colon is not needed here
    |
139 |     requires xs' == xs[a..b];
    |                             ^
```

I assume this has to do with different version of Dafny have slightly different syntax.

**Comment by stefan-aws** [comment]
Indeed, this warning has been introduced with 4.2.0. You can turn off the warnings, if you like. Quoting from https://github.com/dafny-lang/dafny/releases: 

> Added a new CLI option --warn-deprecation, which is on by default
> Extraneous semicolons are now warned about by default; the warning can be disabled using --warn-deprecation:false
> (https://github.com/dafny-lang/dafny/pull/4041)
