### ISSUE TITLE
Need inverse of LemmaCardinalityOfSetNoDuplicates

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/libraries#18]
This lemma proves this implication:
```dafny
  lemma LemmaCardinalityOfSetNoDuplicates<T>(s: seq<T>)
    requires HasNoDuplicates(s)
    ensures |ToSet(s)| == |s|
```

But the opposite implication would also be very useful:
```dafny
  lemma LemmaNoDuplicatesCardinalityOfSet<T>(s: seq<T>)
    requires |ToSet(s)| == |s|
    ensures HasNoDuplicates(s)
```

Especially because `|ToSet(s)| == |s|` is much cheaper to evaluate at runtime than `HasNoDuplicates(s)` would be (if it was a compiled `function method`)

**Comment by gancherj** [comment]
Created pull request. Please let me know if any style fixes are needed :)
