### ISSUE TITLE
Wanted library

### ISSUE THREAD

**Issue by arsalanc-v2** [dafny-lang/libraries#4]
Hello. I am working on gaining more experience with Dafny and thought it would be good to check if there is any library in particular that would be especially welcome in this repository at the moment. Thanks!

**Comment by robin-aws** [comment]
Hi @arsalanc-v2 - in case you're still interested, there's an issue in the main dafny repository with much fresher conversation. Have a look! https://github.com/dafny-lang/dafny/issues/1236
