### ISSUE TITLE
Wrong upper bound of `int16`

### ISSUE THREAD

**Issue by mschlaipfer** [dafny-lang/libraries#6]
The upper bound of `int16` should be `0x8000` (it is `0x80000`)

https://github.com/dafny-lang/libraries/blob/master/src/Std.dfy#L9

**Comment by robin-aws** [comment]
Moot after the big #7 PR, and #15 added https://github.com/dafny-lang/libraries/blob/master/src/BoundedInts.dfy with the correct bounds
